on: [push]
name: Deploy to Azure Container Instances

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
        # checkout the repo
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@master
        
        - name: 'Login via Azure CLI'
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}
            
        - uses: azure/docker-login@v1
          with:
            login-server: ghtesting.azurecr.io
            username: ${{ secrets.ACR_USERNAME }}
            password: ${{ secrets.ACR_PASSWORD }}
        - run: |
            docker build . -t ghtesting.azurecr.io/nodejssampleapp:${{ github.sha }}
            docker push ghtesting.azurecr.io/nodejssampleapp:${{ github.sha }}
            
        - name: 'Deploy to Azure Container Instances'
          uses: 'azure/aci-deploy@v1'
          with:
            resource-group: GitHub_Testing
            dns-name-label: url-for-container
            image: ghtesting.azurecr.io/nodejssampleapp:${{ github.sha }}
            registry-login-server: ghtesting.azurecr.io
            registry-username: ${{ secrets.ACR_USERNAME }}
            registry-password: ${{ secrets.ACR_PASSWORD }}
            name: ghtesting-sample
            location: 'central us'
