on: [push]
name: Linux_Container_Workflow

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
        # checkout the repo
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@master
          
        - uses: azure/docker-login@v1
          with:
            login-server: ghtesting.azurecr.io
            username: ${{ secrets.ACR_USERNAME }}
            password: ${{ secrets.ACR_PASSWORD }}
        - run: |
            docker build . -t ghtesting.azurecr.io/k8sdemo:${{ github.sha }}
            docker push ghtesting.azurecr.io/k8sdemo:${{ github.sha }}
        - run: |
            docker pull ghtesting.azurecr.io/private/k8sdemo:${{ github.sha }}
            docker pull private/k8sdemo:${{ github.sha }}
